db:
  image: postgres:9.4
  volumes:
    - "myvolume:/var/lib/postgresql/data"

redis:
  image: redis
  ports:
    - "6379:6379"

voting-app:
  build: ./voting-app/.
  volumes:
    - ./voting-app:/app
  ports:
    - "5000:80"
  links:
    - redis

worker:
  build: ./worker
  links:
    - redis
    - db

result-app:
  build: ./result-app/.
  volumes:
    - ./result-app:/app
  ports:
    - "5001:80"
  links:
    - db
